# This file is generated by gyp; do not edit.

export builddir_name ?= /Users/garrylachman/GarryProjects/react-native-xmrig/android/libuv/libuv-1.42.0/out
.PHONY: all
all:
	$(MAKE) -C .. run-tests run-benchmarks
