# This file is generated by gyp; do not edit.

export builddir_name ?= /Users/garrylachman/GarryProjects/ReactNativeXMRig/ReactNativeXMRig/android/libuv/libuv-1.23.1/out
.PHONY: all
all:
	$(MAKE) libuv
